baseURL = "https://festive-mestorf-cf09aa.netlify.app/"
paginate = 6
theme = "local"
title = "The Coaching Arc"

[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3

[params]
copyright = "Copyright © 2022 The Coaching Arc"

[params.address]
email = "laurenh@thecoachingarc.com"
phone = "+(44)7816136905"

[[params.social]]
icon = "bi-linkedin"
url = "https://www.linkedin.com/"
weight = 1
[[params.social]]
icon = "bi-instagram"
url = "https://www.instagram.com/"
weight = 2
[[params.social]]
icon = "bi-twitter"
url = "https://twitter.com/"
weight = 3
